# Use a lightweight Python image
FROM python:3.6-alpine

# Set the working directory in the container
WORKDIR /app

# Copy dependencies file
COPY requirements.txt .

# Install dependencies
RUN pip3 install -r requirements.txt

RUN apk add curl

# Copy the application code
COPY . .

# Expose the application port
EXPOSE 5001

# Command to run the application
CMD ["python3", "client.py"]
