apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client-container
        image: quay.io/amitos/client-app:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: shared-config-map
            mountPath: "/etc/shared_config_map"
            readOnly: true
      volumes:
      - name: shared-config-map
        configMap:
          name: my-config-map
            
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client 
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001
  type: NodePort


